/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Config.config;
import javax.swing.JOptionPane;

public class profile extends javax.swing.JFrame {

    private int userId;

    // ✅ Constructor: No-arg version now safe
    public profile() {
    // Now no need for login check here
    this.userId = Config.Session.userId;
    initComponents();
    displayData();
}



    // ✅ Optional: Constructor with explicit userId
    public profile(int userId) {
        if (!Config.Session.isLoggedIn) {
            JOptionPane.showMessageDialog(null, "You must login first!");
            new Main.Login().setVisible(true);
            return;
        }
        this.userId = userId;
        initComponents();
        displayData();
    }

    // Display user data in labels
    private void displayData() {
        try {
            Connection con = config.connectDB();
            String sql = "SELECT fname, lname, a_id, email, type, pass FROM tbl_accounts WHERE a_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userId);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Fn.setText(rs.getString("fname"));
                Ln.setText(rs.getString("lname"));
                id.setText(rs.getString("a_id"));
                Em.setText(rs.getString("email"));
                Ut.setText(rs.getString("type"));
                Pw.setText(rs.getString("pass"));
                fn.setText(rs.getString("fname"));
                ln.setText(rs.getString("lname"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void logout() {
    // 1️⃣ Ask for confirmation
    int choice = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to logout?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    // 2️⃣ If user clicks YES, proceed
    if (choice == JOptionPane.YES_OPTION) {
        // Clear session
        Config.Session.isLoggedIn = false;
        Config.Session.userId = 0; // or -1 if preferred

        // Show login form
        new Main.Login().setVisible(true);

        // Close the current frame
        this.dispose();
    }
    // If NO, do nothing
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Utype = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        Back = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Fn = new javax.swing.JLabel();
        Ln = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        Em = new javax.swing.JLabel();
        Ut = new javax.swing.JLabel();
        Pw = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROFILE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 120));

        Fname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fname.setText("First Name:");
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        Lname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lname.setText("Last Name:");
        jPanel1.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        Id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Id.setText("ID:");
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        Utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Utype.setText("User type:");
        jPanel1.add(Utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        Pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pass.setText("Password:");
        jPanel1.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 26));

        ln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, 26));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 330, 280));

        Back.setBackground(new java.awt.Color(0, 153, 153));
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BACK");

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 150, 40));

        Edit.setBackground(new java.awt.Color(0, 153, 153));
        Edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EDIT");

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 150, 40));

        Email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Email.setText("Email:");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        Fn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 20));

        Ln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 150, 20));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 150, 20));

        Em.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Em, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 150, 20));

        Ut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 150, 20));

        Pw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, 20));

        Logout.setBackground(new java.awt.Color(0, 153, 153));
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGOUT");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        if (Ut.getText().equalsIgnoreCase("Admin")) {
        new adminDashboard().setVisible(true);
    } else if (Ut.getText().equalsIgnoreCase("Student")) {
        new studentDashboard().setVisible(true);
    } else {
        new teacherDashboard().setVisible(true);
    }
    dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        logout();
    }//GEN-LAST:event_LogoutMouseClicked
    public void setColor(JPanel p){
        p.setBackground(new Color(0, 204, 204));
    }
    
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(0, 153, 153));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        if (!Config.Session.isLoggedIn) {
            // Show the login-required notification BEFORE opening profile
            JOptionPane.showMessageDialog(null, "You must login first!");
            new Main.Login().setVisible(true); // open login form
        } else {
            new profile().setVisible(true); // open profile normally
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JPanel Edit;
    private javax.swing.JLabel Em;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fn;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Ln;
    private javax.swing.JLabel Lname;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Pw;
    private javax.swing.JLabel Ut;
    private javax.swing.JLabel Utype;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel ln;
    // End of variables declaration//GEN-END:variables

    private void loadUserData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
