/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.Session;
import Config.config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class subjects extends javax.swing.JFrame {

    /**
     * Creates new form subjects
     */
    public subjects() {
        
        if(!Config.Session.isLoggedIn){
        JOptionPane.showMessageDialog(null, "You must login first!");
        new Main.Login().setVisible(true);
        return; // stop constructor, users form is never initialized
    }
        initComponents();
        displaySubjects();
    }
    void displaySubjects(){
        config cn = new config();
        String sql = "SELECT s_id, s_code, s_name, units, year_level, sem FROM tbl_subjects";
        cn.displayData(sql, subjectstable);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectstable = new javax.swing.JTable();
        back = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        Update = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Add = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Assign = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE SUBJECTS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 130));

        subjectstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(subjectstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 930, 350));

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BACK");
        back.add(jLabel16);
        jLabel16.setBounds(0, 0, 80, 30);

        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 80, 30));

        search.setBackground(new java.awt.Color(0, 153, 153));
        search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SEARCH");
        search.add(jLabel13);
        jLabel13.setBounds(0, 0, 80, 30);

        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 80, 30));
        jPanel1.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 280, 30));

        Update.setBackground(new java.awt.Color(0, 153, 153));
        Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("UPDATE");
        Update.add(jLabel11);
        jLabel11.setBounds(0, 0, 90, 30);

        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, 30));

        Add.setBackground(new java.awt.Color(0, 153, 153));
        Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD");
        Add.add(jLabel15);
        jLabel15.setBounds(0, 0, 90, 30);

        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 30));

        Delete.setBackground(new java.awt.Color(0, 153, 153));
        Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        Delete.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DELETE");
        Delete.add(jLabel12);
        jLabel12.setBounds(0, 0, 90, 30);

        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, 30));

        Assign.setBackground(new java.awt.Color(0, 153, 153));
        Assign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Assign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssignMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ASSIGN SUBJECT");

        javax.swing.GroupLayout AssignLayout = new javax.swing.GroupLayout(Assign);
        Assign.setLayout(AssignLayout);
        AssignLayout.setHorizontalGroup(
            AssignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        AssignLayout.setVerticalGroup(
            AssignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p){
        p.setBackground(new Color(0, 204, 204));
    }
    
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(0, 153, 153));
    }
    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        config conf = new config();
        String keyword = SearchText.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a subject code or name to search.");
            return;
        }
        String sql = "SELECT s_id, s_code, s_name, units, year_level, sem FROM tbl_subjects WHERE s_code LIKE ? OR s_name LIKE ?";
        String like = "%" + keyword + "%";
        conf.displayData(sql, subjectstable, like, like);
        if (subjectstable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No matching record.");
        }
    }//GEN-LAST:event_searchMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int row = subjectstable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Choose a subject to update.");
            return;
        }

        int s_id = Integer.parseInt(subjectstable.getValueAt(row, 0).toString());
        String s_code = subjectstable.getValueAt(row, 1).toString();
        String s_name = subjectstable.getValueAt(row, 2).toString();
        String units = subjectstable.getValueAt(row, 3).toString();
        String yearlvl = subjectstable.getValueAt(row, 4).toString(); // year_level column
        String sem = subjectstable.getValueAt(row, 5).toString();

        UpdateSub up = new UpdateSub(s_id, s_code, s_name, units, yearlvl, sem);
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_UpdateMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        addS Add = new addS();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int row = subjectstable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Choose a subject to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this subject?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        int id = Integer.parseInt(subjectstable.getValueAt(row, 0).toString());

        config con = new config();
        String sql = "DELETE FROM tbl_subjects WHERE s_id = ?";

        con.addRecord(sql, id);

        JOptionPane.showMessageDialog(this, "Subject deleted successfully!");
        displaySubjects();
    }//GEN-LAST:event_DeleteMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        adminDashboardOrig back = new adminDashboardOrig();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void AssignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignMouseClicked
        int row = subjectstable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Choose a subject to assign to a teacher.");
            return;
        }

        int subjectId = Integer.parseInt(subjectstable.getValueAt(row, 0).toString());

        List<Integer> teacherIds = new ArrayList<>();
        List<String> teacherNames = new ArrayList<>();

        try (Connection conn = config.connectDB();
             PreparedStatement ps = conn.prepareStatement("SELECT a_id, fname, lname FROM tbl_accounts WHERE type = 'Teacher' AND status = 'Active'")) {

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    int id = rs.getInt("a_id");
                    String name = rs.getString("fname") + " " + rs.getString("lname");
                    teacherIds.add(id);
                    teacherNames.add(name);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading teachers: " + e.getMessage());
            return;
        }

        if (teacherIds.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No teachers available to assign.");
            return;
        }

        String selectedTeacher = (String) JOptionPane.showInputDialog(
                this,
                "Select a teacher:",
                "Assign Subject",
                JOptionPane.PLAIN_MESSAGE,
                null,
                teacherNames.toArray(new String[0]),
                teacherNames.get(0)
        );

        if (selectedTeacher == null) {
            return;
        }

        int teacherIndex = teacherNames.indexOf(selectedTeacher);
        if (teacherIndex < 0) {
            return;
        }
        int teacherId = teacherIds.get(teacherIndex);

        int confirm = JOptionPane.showConfirmDialog(this, "Assign this subject to " + selectedTeacher + "?", "Confirm Assign", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        config cn = new config();
        String sql = "INSERT INTO tbl_subjects_handled(a_id, s_id) VALUES(?, ?)";
        cn.addRecord(sql, teacherId, subjectId);

        JOptionPane.showMessageDialog(this, "Subject assigned successfully!");
    }//GEN-LAST:event_AssignMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        setColor(Add);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        resetColor(Add);
    }//GEN-LAST:event_AddMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        setColor(Update);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        resetColor(Update);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        setColor(Delete);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        resetColor(Delete);
    }//GEN-LAST:event_DeleteMouseExited

    private void AssignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignMouseEntered
        setColor(Assign);
    }//GEN-LAST:event_AssignMouseEntered

    private void AssignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignMouseExited
        resetColor(Assign);
    }//GEN-LAST:event_AssignMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        setColor(search);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        setColor(search);
    }//GEN-LAST:event_searchMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        setColor(back);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        setColor(back);
    }//GEN-LAST:event_backMouseExited

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JPanel Assign;
    private javax.swing.JPanel Delete;
    private javax.swing.JTextField SearchText;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel search;
    private javax.swing.JTable subjectstable;
    // End of variables declaration//GEN-END:variables
}
